### PR TITLE
LPS-70396 For special cases (Frontpage) that doesn't have a user, we should introduce a name. By now lets be consistent with "com/liferay/wiki/web/internal/display/context/util/WikiSocialActivityHelper.java:110", but should be configurable (or get the group name????

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@hudakl 

Please check my changes and resend.

I have to discuss with collab team about the last commit.

Thanks!!

**Comment by hudakl** [comment]
Hi Roberto,

Your changes look good and are working correctly.
Please let me know if you came to a decision about the last commit and I'll resend the fix accordingly, if that's OK for you.

Thanks,
Laci

**Comment by robertoDiaz** [comment]
Ok, I'm closing this and I'll resend to @sergiogonzalez

Thank you!!!

**Comment by robertoDiaz** [comment]
see https://github.com/sergiogonzalez/liferay-portal/pull/3795

**Pull request closed without merging**
