### PR TITLE
LPS-76663 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @hudakl 
I did a different fix for LPS-76663 and the test you wrote is passing.
Can you please check if the logic looks good to you so I can fwd it to Brian?
Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by hudakl** [comment]
Hi Sergio,

I tested your logic and it works for me as well.

Thanks,
Laci

**Comment by sergiogonzalez** [comment]
Sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/58623

**Pull request closed without merging**
