### PR TITLE
LPS-76663 We should only modify the thread once the message has pass the workflow process. We should always update the thread when the message is updated.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hey @hudakl 

Can you test my changes?? I've test it and it seems to work as expected. Can you assert that??

Thanks!!

**Comment by robertoDiaz** [comment]
ci:test

**Comment by hudakl** [comment]
Hi,

I tested your changes and it worked for me too.
Thanks for the correction.

**Comment by hudakl** [comment]
Hi Roberto,

Do you have any updates concerning this pull request?

Thanks,
Laci

**Comment by robertoDiaz** [comment]
Please, send it to the release team.

**Pull request closed without merging**
