### PR TITLE
LPS-105723 Escape URL to avoid XSS

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @hudakl ,

Can you test whether this PR solves LPS-105723? If so, you can directly send it to the Product Team.

Thanks.

Regards

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by hudakl** [comment]
Hi @antonio-ortega ,

I checked your changes and the issue is reproducible with your changes, because the problematic part is the deltaURL which is also based on the url and you missed escaping that.
Nonetheless, I agree that since we apply further modifications to the url we should indeed escape it upon usage. So, if you agree I add the HtmlUtil.escapeURL to creating the deltaURL and forward the pull to the product team.

Thanks,
Laci

**Comment by antonio-ortega** [comment]
Hi @hudakl ,

Keep in mind what I said [here](https://github.com/antonio-ortega/liferay-portal/pull/87#issuecomment-566980665), please.

If you are talking about the use of deltaURL under page_iterator/start.jsp I guess you mean [this use](https://github.com/hudakl/liferay-portal/blob/9c10d2b780e4fa398c0acc248f9eed52b44486be/portal-web/docroot/html/taglib/ui/page_iterator/start.jsp#L242) of it. So you need to escape there.

If you are talking about the use of deltaURL under page_iterator/lexicon/start.jsp, there is not a direct use of it, but we are using it to [build](https://github.com/hudakl/liferay-portal/blob/9c10d2b780e4fa398c0acc248f9eed52b44486be/portal-web/docroot/html/taglib/ui/page_iterator/lexicon/start.jsp#L101) curDeltaURL, which is finally use [here](https://github.com/hudakl/liferay-portal/blob/9c10d2b780e4fa398c0acc248f9eed52b44486be/portal-web/docroot/html/taglib/ui/page_iterator/lexicon/start.jsp#L105) in a HTML context.

Thanks.

Regards.

**Comment by hudakl** [comment]
Hi @antonio-ortega 

Keeping that in mind I can indeed call the escapeURL at those points.

Regards,
Laci

**Comment by antonio-ortega** [comment]
@hudakl ,

As I said you need to escape in context. You can not use escapeURL as a general rule for all the cases. 

Please, review my comments. If there is anything you can't understand, let me know.

**Comment by hudakl** [comment]
@antonio-ortega ,

What I don't fully understand what is wrong with the escapeURL method. I thought that is to be used especially for URLs, like in this case, so it could be used in href.

Did I misunderstand something? If so, what is exactly the purpose of that method?

**Comment by samuelkong** [comment]
@hudakl 
It's all about context. For example:

    String param = "a&b.txt";
    String url = "http://example.com?page=" + HtmlUtil.escapeURL(param);
    System.out.println(url);

`escapeURL` is needed because `&` is a reserved character in URLs. So if you want a valid URL, you will need to first encode `param`. This will create a valid URL that you can paste into your browser's address bar.

Side Note: `escapeURL` is a misnomer. The method should probably be called "encode" rather than "escape".

If `param` is from an untrusted source (e.g., user input) and you plan on inserting `param` into an HTML, than you'll need to escape it using `escape`, `escapeAttribute`, `escapeJS` or `escapeCSS` depending on the context. For example:

    <%
    String param = ParamUtil.get("file");
    %>
    <div>http://example.com?page=<%= HtmlUtil.escape(param) %></div>

Now let's say that untrusted input may contain characters that are illegal in a URL, than you'll actually need:

    <%
    String param = ParamUtil.get("file");  // Let's say the value is: a&b.txt
    %>
    <div>http://example.com?page=<%= HtmlUtil.escape(HtmlUtil.escapeURL(param)) %></div>

Using `escape` alone will prevent XSS but may leave you with an invalid URL. On the other hand, using `escapeURL` alone will give you a valid URL but may leave you vulnerable to XSS. As far as preventing XSS is concerned, `escapeURL` is not sufficient.

**Comment by hudakl** [comment]
Hi @samuelkong ,

Thanks for the explanation. I will change the fix accordingly and resend it.

Regards,
Laci

**Pull request closed without merging**
